ALTER TABLE `TickerItem`
  ADD COLUMN `species` VARCHAR(191) NULL,
  ADD COLUMN `location` VARCHAR(191) NULL,
  ADD COLUMN `company` VARCHAR(191) NULL,
  ADD COLUMN `product` VARCHAR(191) NULL,
  ADD COLUMN `bagSize` VARCHAR(191) NULL,
  ADD COLUMN `couponCode` VARCHAR(191) NULL,
  ADD COLUMN `expiryDate` DATETIME(3) NULL,
  ADD COLUMN `campaignName` VARCHAR(191) NULL;
