"use client";

/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useState } from "react";
import { ArrowUpRight, BarChart3, BookOpen, CalendarDays, ExternalLink, MousePointerClick, Users } from "lucide-react";

type AnalyticsData = {
  success: boolean; configured: boolean; message?: string; detailNotice?: string | null;
  cards?: { articleViews: number; uniqueReaders: number; tickerClicks: number; telaquaClicks: number; articleViewsChange: number | null };
  articles?: { id: string; title: string; category: string; views: number; uniqueReaders: number; averageReadingTime: number; publicationDate: string }[];
  tickers?: { id: string; campaign: string; destinationUrl: string; impressions: number; clicks: number; uniqueClicks: number; ctr: number; status: string }[];
};

const presets = [{ value: "today", label: "Today" }, { value: "7", label: "Last 7 Days" }, { value: "30", label: "Last 30 Days" }, { value: "custom", label: "Custom" }];
const format = (value: number) => new Intl.NumberFormat("en-IN").format(value);

export function AnalyticsDashboard() {
  const [range, setRange] = useState("30");
  const [start, setStart] = useState(""); const [end, setEnd] = useState("");
  const [data, setData] = useState<AnalyticsData | null>(null); const [loading, setLoading] = useState(true);
  const [selectedArticle, setSelectedArticle] = useState<NonNullable<AnalyticsData["articles"]>[number] | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    const query = new URLSearchParams({ range }); if (range === "custom" && start && end) { query.set("start", start); query.set("end", end); }
    try { const response = await fetch(`/api/admin/analytics?${query}`, { cache: "no-store" }); const body = await response.json(); setData(body); }
    catch { setData({ success: false, configured: true, message: "Analytics could not be loaded. Please try again." }); }
    finally { setLoading(false); }
  }, [range, start, end]);
  useEffect(() => { if (range !== "custom" || (start && end)) void load(); }, [load, range, start, end]);

  const cards = data?.cards;
  return <div className="mx-auto max-w-7xl space-y-7">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-600">Performance</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Analytics</h2><p className="mt-2 text-sm text-slate-500">Understand how people are using Shrimp.News.</p></div><div className="flex flex-wrap gap-2 rounded-2xl bg-white p-2 shadow-sm ring-1 ring-slate-200/80" aria-label="Analytics date range">{presets.map((preset) => <button key={preset.value} onClick={() => setRange(preset.value)} className={`rounded-xl px-3.5 py-2 text-xs font-bold transition ${range === preset.value ? "bg-[#0B4F7A] text-white" : "text-slate-500 hover:bg-slate-50"}`}>{preset.label}</button>)}</div></div>
    {range === "custom" ? <div className="flex flex-wrap items-end gap-3 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200/80"><DateInput label="From" value={start} onChange={setStart} /><DateInput label="To" value={end} onChange={setEnd} /><button onClick={() => void load()} disabled={!start || !end} className="h-10 rounded-xl bg-[#0B4F7A] px-5 text-sm font-bold text-white disabled:opacity-40">Apply</button></div> : null}
    {loading ? <div className="rounded-2xl bg-white p-16 text-center text-sm text-slate-500 shadow-sm ring-1 ring-slate-200/80">Loading Google Analytics data…</div> : !data?.configured ? <SetupState /> : !data.success ? <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700"><p className="font-bold">Google Analytics could not be reached</p><p className="mt-1">{data.message}</p></div> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BookOpen} label="Total Article Views" value={format(cards?.articleViews || 0)} change={cards?.articleViewsChange} /><MetricCard icon={Users} label="Unique Readers" value={format(cards?.uniqueReaders || 0)} /><MetricCard icon={MousePointerClick} label="Ticker Clicks" value={format(cards?.tickerClicks || 0)} /><MetricCard icon={ExternalLink} label="Telaqua Website Clicks" value={format(cards?.telaquaClicks || 0)} /></div>
      {data.detailNotice ? <div className="rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-200">{data.detailNotice}</div> : null}
      <TableSection title="Article Performance" subtitle="Click an article row to see its GA4 details."><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Article</th><th className="px-4 py-4 text-right">Views</th><th className="px-4 py-4 text-right">Unique Readers</th><th className="px-4 py-4 text-right">Avg. Reading Time</th><th className="px-5 py-4 text-right">Published</th></tr></thead><tbody className="divide-y divide-slate-100">{data.articles?.length ? data.articles.map((row) => <tr key={`${row.id}-${row.title}`} onClick={() => setSelectedArticle(row)} className="cursor-pointer hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-slate-800">{row.title}</p><p className="mt-1 text-xs text-slate-400">{row.category}</p></td><td className="px-4 py-4 text-right font-semibold">{format(row.views)}</td><td className="px-4 py-4 text-right">{format(row.uniqueReaders)}</td><td className="px-4 py-4 text-right">{Math.floor(row.averageReadingTime / 60)}m {row.averageReadingTime % 60}s</td><td className="px-5 py-4 text-right text-slate-500">{row.publicationDate ? new Date(row.publicationDate).toLocaleDateString("en-IN") : "—"}</td></tr>) : <EmptyRow columns={5} label="No article views were recorded for this period." />}</tbody></table></TableSection>
      <TableSection title="Ticker Performance" subtitle="See which ticker campaigns are driving visits."><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Ticker Campaign</th><th className="px-4 py-4 text-right">Impressions</th><th className="px-4 py-4 text-right">Clicks</th><th className="px-4 py-4 text-right">Unique Clicks</th><th className="px-4 py-4 text-right">CTR</th><th className="px-5 py-4 text-right">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{data.tickers?.length ? data.tickers.map((row) => <tr key={`${row.id}-${row.campaign}`} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-slate-800">{row.campaign}</p>{row.destinationUrl ? <a href={row.destinationUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-xs text-cyan-700 hover:underline">{row.destinationUrl}<ArrowUpRight size={11} /></a> : <p className="mt-1 text-xs text-slate-400">No destination URL</p>}</td><td className="px-4 py-4 text-right">{format(row.impressions)}</td><td className="px-4 py-4 text-right font-semibold">{format(row.clicks)}</td><td className="px-4 py-4 text-right">{format(row.uniqueClicks)}</td><td className="px-4 py-4 text-right font-bold text-[#0B4F7A]">{row.ctr.toFixed(1)}%</td><td className="px-5 py-4 text-right"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.status === "Active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{row.status}</span></td></tr>) : <EmptyRow columns={6} label="No ticker clicks were recorded for this period." />}</tbody></table></TableSection>
      {selectedArticle ? <div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/50 p-0 sm:items-center sm:p-5" onClick={() => setSelectedArticle(null)}><div className="w-full max-w-lg rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-cyan-600">Article details</p><h3 className="mt-2 text-xl font-black text-slate-900">{selectedArticle.title}</h3></div><button onClick={() => setSelectedArticle(null)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold">Close</button></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><Detail label="Total views" value={format(selectedArticle.views)} /><Detail label="Unique readers" value={format(selectedArticle.uniqueReaders)} /><Detail label="Average reading time" value={`${Math.floor(selectedArticle.averageReadingTime / 60)}m ${selectedArticle.averageReadingTime % 60}s`} /><Detail label="Publication date" value={selectedArticle.publicationDate ? new Date(selectedArticle.publicationDate).toLocaleDateString("en-IN") : "—"} /></dl></div></div> : null}
    </>}
  </div>;
}

function MetricCard({ icon: Icon, label, value, change }: { icon: typeof BarChart3; label: string; value: string; change?: number | null }) { return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/80"><div className="flex items-start justify-between"><p className="text-sm font-bold text-slate-600">{label}</p><span className="rounded-xl bg-cyan-50 p-2 text-[#0B4F7A]"><Icon size={18} /></span></div><p className="mt-5 text-3xl font-black tracking-tight text-slate-950">{value}</p>{change != null ? <p className={`mt-2 text-xs font-semibold ${change >= 0 ? "text-emerald-600" : "text-red-600"}`}>{change >= 0 ? "+" : ""}{change.toFixed(1)}% compared with previous period</p> : <p className="mt-2 text-xs text-slate-400">Selected period</p>}</div>; }
function TableSection({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200/80"><div className="px-5 py-5"><h3 className="text-lg font-black text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><div className="overflow-x-auto border-t border-slate-100">{children}</div></section>; }
function DateInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-bold text-slate-600">{label}<input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block h-10 rounded-xl border border-slate-200 px-3 text-sm" /></label>; }
function EmptyRow({ columns, label }: { columns: number; label: string }) { return <tr><td colSpan={columns} className="px-5 py-12 text-center text-slate-400">{label}</td></tr>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 font-black text-slate-900">{value}</dd></div>; }
function SetupState() { return <div className="rounded-2xl bg-white p-8 text-center shadow-sm ring-1 ring-slate-200/80"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-50 text-[#0B4F7A]"><BarChart3 size={25} /></span><h3 className="mt-5 text-xl font-black text-slate-900">Connect Google Analytics</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">Add the GA4 property ID and service-account credentials to the server environment to display real analytics. No sample numbers are shown.</p><div className="mx-auto mt-5 flex max-w-md items-center justify-center gap-2 rounded-xl bg-slate-50 px-4 py-3 text-xs font-semibold text-slate-600"><CalendarDays size={15} /> Visitor tracking starts when NEXT_PUBLIC_GA_MEASUREMENT_ID is configured.</div></div>; }
